/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.work.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.opensymphony.xwork2.ActionSupport;
import com.work.Sc;
import com.work.struts.form.CancelScForm;

public class CancelScAction extends ActionSupport {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CancelScForm cancelScForm = (CancelScForm) form;
		String sno=cancelScForm.getSno();
		String[] cnos=cancelScForm.getCno();
		if(cnos!=null){
		  for(int i=0;i<cnos.length;i++)
			  Sc.deleteSc(sno, cnos[i]);	
		}
		return(mapping.findForward("cancelSuccess"));
	}
}