/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.work.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Course;
import com.jspdev.biyesheji.Grade;
import com.jspdev.biyesheji.GradePK;
import com.jspdev.biyesheji.Student;
import com.yourcompany.struts.form.GradeForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2008
 * 
 * XDoclet definition:
 * @struts.action path="/grade" name="gradeForm" input="/form/addGrade.jsp" scope="request" validate="true"
 */
public class GradeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		GradeForm gradeForm = (GradeForm) form;// TODO Auto-generated method stub
		Grade grade=new Grade();
		Student student=Student.getStudent(gradeForm.getSnumber());
		Course course=Course.getCourse(gradeForm.getCnumber());
		GradePK gradePK=new GradePK(student,course);
		grade.setId(gradePK);
		grade.setChongXiu(gradeForm.getChongXiu());
		grade.setGrade(Float.parseFloat(gradeForm.getGrade()));
		grade.setTerm(Long.parseLong(gradeForm.getTerm()));
		grade.setYear(gradeForm.getYear());	
		if(!(grade.isTrue(gradePK)))
			Grade.addGrade(grade);
		return(mapping.findForward("addSuccess"));
	}
}