/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.work.struts.action;
import com.jspdev.biyesheji.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.PasswordForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-09-2008
 * 
 * XDoclet definition:
 * @struts.action path="/password" name="passwordForm" input="/form/password.jsp" scope="request" validate="true"
 */
public class PasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PasswordForm passwordForm = (PasswordForm) form;// TODO Auto-generated method stub
	    String s=passwordForm.getStuId();
	    String t=passwordForm.getTeaId();
	 try{
		 if(s!=null){
				
		    	//  if(passwordForm.getPassword1().equals(student.getPassword())&&passwordForm.getPassword2().equals(passwordForm.getPassword3())&&!(passwordForm.getPassword2().equals(passwordForm.getPassword1()))){
		    		if(passwordForm.getPassword1().equals(passwordForm.getPassword2())){		
		    			Student.changePassword(passwordForm);
		    		}else{
		    			request.setAttribute("flag", "true");
		    			return mapping.findForward("changeFailure");
		    		}
		    }
		    else if(t!=null){
		
		    		if(passwordForm.getPassword1().equals(passwordForm.getPassword2())){		
		    			Teacher.changePassword(passwordForm);
		    		}else{
		    			request.setAttribute("flag", "true");
		    			return mapping.findForward("changeFailure");
		    		}	    		
		    }
	 }catch(Exception e ){}
	    
	    
	//	    return mapping.findForward("changeFailure");
		return(mapping.findForward("changeSuccess"));
		
	}
}