/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.work.struts.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Student;
import com.yourcompany.struts.form.StuInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2008
 * 
 * XDoclet definition:
 * @struts.action path="/stuInfo" name="stuInfoForm" input="/form/changeStuInfo.jsp" scope="request" validate="true"
 */
public class StuInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		StuInfoForm stuInfoForm = (StuInfoForm) form;// TODO Auto-generated method stub
		Student student=Student.getStudent(stuInfoForm.getNumber());
		student.chahgeStuInfo(stuInfoForm);
		return(mapping.findForward("changeSuccess"));
	}
}