/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.work.struts.action;

import java.util.Collection;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Student;
import com.jspdev.biyesheji.Teacher;
import com.yourcompany.struts.form.TeachersQueryForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-15-2008
 * 
 * XDoclet definition:
 * @struts.action path="/teachersQuery" name="teachersQueryForm" input="/form/teachersQuery.jsp" scope="request" validate="true"
 */
public class TeachersQueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TeachersQueryForm teachersQueryForm = (TeachersQueryForm) form;// TODO Auto-generated method stub
		Teacher teacher=new Teacher();
		HttpSession session=request.getSession();
		try{
			if(!(teachersQueryForm.getId().equals(""))){
				String hql="from Teacher t where t.id='"+teachersQueryForm.getId()+"'";
				Collection collection=teacher.queryOperator(hql);
			    session.setAttribute("teachers", collection);
			}
			else if(!(teachersQueryForm.getDepartment().equals(""))){
				if(!(teachersQueryForm.getPost().equals(""))){
					if(!(teachersQueryForm.getAge().equals(""))){
						String hql="from Teacher t where t.department='"+teachersQueryForm.getDepartment()+"' and t.post='"+teachersQueryForm.getPost()+"' and t.age>="+Long.parseLong(teachersQueryForm.getAge())+" and t.age<"+(Long.parseLong(teachersQueryForm.getAge())+new Long(10));
						Collection collection=teacher.queryOperator(hql);
						session.setAttribute("teachers", collection);
					}
					else{
						String hql="from Teacher t where t.department='"+teachersQueryForm.getDepartment()+"' and t.post='"+teachersQueryForm.getPost()+"'";
						System.out.println(hql);
						Collection collection=teacher.queryOperator(hql);
						session.setAttribute("teachers", collection);
					}
				}
				else{
					if(!(teachersQueryForm.getAge().equals(""))){
						String hql="from Teacher t where t.department='"+teachersQueryForm.getDepartment()+"' and t.age>="+Long.parseLong(teachersQueryForm.getAge())+" and t.age<"+(Long.parseLong(teachersQueryForm.getAge())+new Long(10));
						Collection collection=teacher.queryOperator(hql);
						session.setAttribute("teachers", collection);
					}
					else{
						String hql="from Teacher t where t.department='"+teachersQueryForm.getDepartment()+"'";
						Collection collection=teacher.queryOperator(hql);
						session.setAttribute("teachers", collection);
					}
				}	
			}
			else if(!(teachersQueryForm.getPost().equals(""))){
				if(!(teachersQueryForm.getAge().equals(""))){
					String hql="from Teacher t where t.post='"+teachersQueryForm.getPost()+"' and t.age>="+Long.parseLong(teachersQueryForm.getAge())+" and t.age<"+(Long.parseLong(teachersQueryForm.getAge())+new Long(10));
					Collection collection=teacher.queryOperator(hql);
					session.setAttribute("teachers", collection);
				}
				else{
					String hql="from Teacher t where t.post='"+teachersQueryForm.getPost()+"'";
					Collection collection=teacher.queryOperator(hql);
					session.setAttribute("teachers", collection);
				}
			}
			else{
				if(!(teachersQueryForm.getAge().equals(""))){
					String hql="from Teacher t where t.age>="+Long.parseLong(teachersQueryForm.getAge())+" and t.age<"+(Long.parseLong(teachersQueryForm.getAge())+new Long(10));
					Collection collection=teacher.queryOperator(hql);
					session.setAttribute("teachers", collection);
				}
				else{
					Collection collection=teacher.getAllTeachers();
					session.setAttribute("teachers", collection);
				}
			}
		}
		catch(Exception e){}
		
		return(mapping.findForward("queryResult"));
	}
}