/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import java.util.Collection;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Course;
import com.yourcompany.struts.form.CoursesQueryForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-18-2008
 * 
 * XDoclet definition:
 * @struts.action path="/coursesQuery" name="coursesQueryForm" input="/form/coursesQuery.jsp" scope="request" validate="true"
 */
public class CoursesQueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CoursesQueryForm coursesQueryForm = (CoursesQueryForm) form;// TODO Auto-generated method stub
		Course course=new Course();
		HttpSession session=request.getSession();
		try{
			if(!(coursesQueryForm.getId().equals(""))){
				String hql="from Course c where c.id='"+coursesQueryForm.getId()+"'";
				Collection collection=course.queryOperator(hql);
			    session.setAttribute("courses", collection);
			}
			else if(!(coursesQueryForm.getCredit().equals(""))){
				if(!(coursesQueryForm.getType().equals(""))){
					String hql="from Course c where c.credit="+Long.parseLong(coursesQueryForm.getCredit())+" and c.type='"+coursesQueryForm.getType()+"'";
					Collection collection=course.queryOperator(hql);
					session.setAttribute("courses", collection);
				}
				else{
					String hql="from Course c where c.credit="+Long.parseLong(coursesQueryForm.getCredit());
					Collection collection=course.queryOperator(hql);
					session.setAttribute("courses", collection);
				}	
			}
			else{
				if(!(coursesQueryForm.getType().equals(""))){
					String hql="from Course c where c.type='"+coursesQueryForm.getType()+"'";
					Collection collection=course.queryOperator(hql);
					session.setAttribute("courses", collection);
				}
				else{
					Collection collection=course.getCourses();
					session.setAttribute("courses", collection);
				}
			}	
		}
		catch(Exception e){}
		
		return(mapping.findForward("queryResult"));
	}
}