/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Course;
import com.yourcompany.struts.form.CourseForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-21-2008
 * 
 * XDoclet definition:
 * @struts.action path="/course" name="courseForm" input="/form/addCourse.jsp" scope="request" validate="true"
 */
public class CourseAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CourseForm courseForm = (CourseForm) form;// TODO Auto-generated method stub
		Course course=new Course(courseForm.getId(),courseForm.getName(),Long.parseLong(courseForm.getCredit()),courseForm.getTeacher(),courseForm.getTime(),courseForm.getAddress(),courseForm.getType());
		if(!(course.isTrue(course.getId())))
		Course.addCourse(course);
		return mapping.findForward("addSuccess");	
	}
}