/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Student;
import com.yourcompany.struts.form.DeleteStudentsForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-15-2008
 * 
 * XDoclet definition:
 * @struts.action path="/deleteStudents" name="deleteStudentsForm" input="/form/studentsQueryResult.jsp" scope="request" validate="true"
 */
public class DeleteStudentsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		DeleteStudentsForm deleteStudentsForm = (DeleteStudentsForm) form;// TODO Auto-generated method stub
		String[] id=deleteStudentsForm.getId();
		if(id!=null){
			for(int i=0;i<id.length;i++){
				Student.deleteStudent(id[i]);
			}
		}
		return(mapping.findForward("deleteSuccess"));
	}
}