/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Course;
import com.yourcompany.struts.form.DeleteCoursesForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-18-2008
 * 
 * XDoclet definition:
 * @struts.action path="/deleteCourses" name="deleteCoursesForm" input="/form/coursesQueryResult.jsp" scope="request" validate="true"
 * @struts.action-forward name="deleteSuccess" path="/form/nothing.jsp"
 */
public class DeleteCoursesAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		DeleteCoursesForm deleteCoursesForm = (DeleteCoursesForm) form;// TODO Auto-generated method stub
		String[] id=deleteCoursesForm.getId();
		if(id!=null){
			for(int i=0;i<id.length;i++){
				Course.deleteCourse(id[i]);
			}
		}
		return(mapping.findForward("deleteSuccess"));
	}
}