/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import java.util.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
//import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;

import com.jspdev.biyesheji.Grade;
import com.yourcompany.struts.form.GradeQueryForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-29-2008
 * 
 * XDoclet definition:
 * @struts.action path="/gradeQuery" name="gradeQueryForm" input="/form/gradeQuery.jsp" scope="request" validate="true"
 */
public class GradeQueryAction extends LookupDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	protected Map getKeyMethodMap() { 
        Map map = new HashMap(); 
        map.put("button.termGrade", "termGrade"); 
        map.put("button.yearGrade", "yearGrade"); 
        map.put("button.allGrade", "allGrade");
        return map; 
    } 

    public ActionForward termGrade(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response)throws Exception { 
        GradeQueryForm gradeQueryForm=(GradeQueryForm)form;
        Grade grade=new Grade();
        Collection collection=grade.getTermGrades(gradeQueryForm.getSno(),gradeQueryForm.getYear(),Long.parseLong(gradeQueryForm.getTerm()));
        HttpSession session=request.getSession();
        session.setAttribute("termGrade", collection);
        return(mapping.findForward("byTerm"));
    } 

    public ActionForward yearGrade(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response)throws Exception {  
    	GradeQueryForm gradeQueryForm=(GradeQueryForm)form;
        Grade grade=new Grade();
        Collection collection=grade.getYearGrades(gradeQueryForm.getSno(),gradeQueryForm.getYear());
        HttpSession session=request.getSession();
        session.setAttribute("yearGrade", collection);
        return(mapping.findForward("byYear"));
    } 
    
    public ActionForward allGrade(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response)throws Exception { 
    	GradeQueryForm gradeQueryForm=(GradeQueryForm)form;
        Grade grade=new Grade();
        Collection collection=grade.getAllGrades(gradeQueryForm.getSno());
        HttpSession session=request.getSession();
        session.setAttribute("allGrade", collection);
        return(mapping.findForward("byAll"));    
    }       
}