/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Message;
import com.yourcompany.struts.form.MessageForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2008
 * 
 * XDoclet definition:
 * @struts.action path="/message" name="messageForm" input="/form/addMessage.jsp" scope="request" validate="true"
 */
public class MessageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		MessageForm messageForm = (MessageForm) form;// TODO Auto-generated method stub
		Message message=new Message();
		message.setContent(messageForm.getContent());
		message.setEmail(messageForm.getEmail());
		message.setName(messageForm.getName());
		message.setTime(messageForm.getTime());
		message.setTitle(messageForm.getTitle());
	//	message.setId(message.getMessageCount()+new Long(1));
		Message.addMessage(message);
		return mapping.findForward("addSuccess");
	}
}