/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Note;
import com.yourcompany.struts.form.NoteForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2008
 * 
 * XDoclet definition:
 * @struts.action path="/note" name="noteForm" input="/form/addNotes.jsp" scope="request" validate="true"
 */
public class NoteAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		NoteForm noteForm = (NoteForm) form;// TODO Auto-generated method stub
		Note note=new Note();
		note.updateNote(noteForm.getContent(), new java.util.Date().toLocaleString());
		return (mapping.findForward("addNoteSuccess"));
	}
}