/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Course;
import com.jspdev.biyesheji.Sc;
import com.yourcompany.struts.form.ScForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2008
 * 
 * XDoclet definition:
 * @struts.action path="/sc" name="scForm" input="/form/choseCourse.jsp" scope="request" validate="true"
 */
public class ScAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		ScForm scForm = (ScForm) form;// TODO Auto-generated method stub	
		String sno=scForm.getSno();
        String[] cnos=scForm.getCno();
        if(cnos!=null){
		for(int i=0;i<cnos.length;i++){
			Sc sc=new Sc();
			Course course=Course.getCourse(cnos[i]);
			sc.setSno(sno);
			sc.setName(course.getName());
			sc.setCno(cnos[i]);
			sc.setTeacher(course.getTeacher());
			sc.setCredit(course.getCredit());
			sc.setType(course.getType());
			sc.setTime(course.getTime());
			sc.setAddress(course.getAddress());
			sc.setSelected("false");
			if(!(sc.isTrue(sc.getSno(), sc.getCno())))
			Sc.addSc(sc);
		}}
		return(mapping.findForward("choseSuccess"));
	}
}