/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.njust.tms.action;

import java.util.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Student;
import com.yourcompany.struts.form.StudentsQueryForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-15-2008
 * 
 * XDoclet definition:
 * @struts.action path="/studentsQuery" name="studentsQueryForm" input="/form/studentsQuery.jsp" scope="request" validate="true"
 */
public class StudentsQueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentsQueryForm studentsQueryForm = (StudentsQueryForm) form;// TODO Auto-generated method stub
		Student student=new Student();
		HttpSession session=request.getSession();
		try{
			if(!(studentsQueryForm.getId().equals(""))){
				String hql="from Student s where s.id='"+studentsQueryForm.getId()+"'";
				Collection collection=student.queryOperator(hql);
			    session.setAttribute("students", collection);
			}
			else if(!(studentsQueryForm.getCollege().equals(""))){
				if(!(studentsQueryForm.getDepartment().equals(""))){
					if(!(studentsQueryForm.getInTime().equals(""))){
						String hql="from Student s where s.college='"+studentsQueryForm.getCollege()+"' and s.department='"+studentsQueryForm.getDepartment()+"' and s.inTime='"+studentsQueryForm.getInTime()+"'";
						Collection collection=student.queryOperator(hql);
						session.setAttribute("students", collection);
					}
					else{
						String hql="from Student s where s.college='"+studentsQueryForm.getCollege()+"' and s.department='"+studentsQueryForm.getDepartment()+"'";
						Collection collection=student.queryOperator(hql);
						session.setAttribute("students", collection);
					}
				}
				else{
					if(!(studentsQueryForm.getInTime().equals(""))){
						String hql="from Student s where s.college='"+studentsQueryForm.getCollege()+"' and s.inTime='"+studentsQueryForm.getInTime()+"'";
						Collection collection=student.queryOperator(hql);
						session.setAttribute("students", collection);
					}
					else{
						String hql="from Student s where s.college='"+studentsQueryForm.getCollege()+"'";
						Collection collection=student.queryOperator(hql);
						session.setAttribute("students", collection);
					}
				}	
			}
			else if(!(studentsQueryForm.getDepartment().equals(""))){
				if(!(studentsQueryForm.getInTime().equals(""))){
					String hql="from Student s where s.department='"+studentsQueryForm.getDepartment()+"' and s.inTime='"+studentsQueryForm.getInTime()+"'";
					Collection collection=student.queryOperator(hql);
					session.setAttribute("students", collection);
				}
				else{
					String hql="from Student s where s.department='"+studentsQueryForm.getDepartment()+"'";
					Collection collection=student.queryOperator(hql);
					session.setAttribute("students", collection);
				}
			}
			else{
				if(!(studentsQueryForm.getInTime().equals(""))){
					String hql="from Student s where s.inTime='"+studentsQueryForm.getInTime()+"'";
					Collection collection=student.queryOperator(hql);
					session.setAttribute("students", collection);
				}
				else{
					Collection collection=student.getAllStudents();
					session.setAttribute("students", collection);
				}
			}
		}
		catch(Exception e){}
		
		return(mapping.findForward("queryResult"));
	}
}