/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.work.struts.form;

import javax.servlet.http.HttpServletRequest;
import com.opensymphony.xwork2.ActionSupport;

public class GradeForm extends ActionSupport {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** year property */
	private String year;

	/** term property */
	private String term;

	/** grade property */
	private String grade;

	/** chongXiu property */
	private String chongXiu;

	/** snumber property */
	private String snumber;

	/** cnumber property */
	private String cnumber;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the year.
	 * @return String
	 */
	public String getYear() {
		return year;
	}

	/** 
	 * Set the year.
	 * @param year The year to set
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/** 
	 * Returns the term.
	 * @return String
	 */
	public String getTerm() {
		return term;
	}

	/** 
	 * Set the term.
	 * @param term The term to set
	 */
	public void setTerm(String term) {
		this.term = term;
	}

	/** 
	 * Returns the grade.
	 * @return String
	 */
	public String getGrade() {
		return grade;
	}

	/** 
	 * Set the grade.
	 * @param grade The grade to set
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/** 
	 * Returns the chongXiu.
	 * @return String
	 */
	public String getChongXiu() {
		return chongXiu;
	}

	/** 
	 * Set the chongXiu.
	 * @param chongXiu The chongXiu to set
	 */
	public void setChongXiu(String chongXiu) {
		this.chongXiu = chongXiu;
	}

	/** 
	 * Returns the snumber.
	 * @return String
	 */
	public String getSnumber() {
		return snumber;
	}

	/** 
	 * Set the snumber.
	 * @param snumber The snumber to set
	 */
	public void setSnumber(String snumber) {
		this.snumber = snumber;
	}

	/** 
	 * Returns the cnumber.
	 * @return String
	 */
	public String getCnumber() {
		return cnumber;
	}

	/** 
	 * Set the cnumber.
	 * @param cnumber The cnumber to set
	 */
	public void setCnumber(String cnumber) {
		this.cnumber = cnumber;
	}

}